### PR TITLE
add @Symbol to be able to easily use the plugin in a declarative pipeline

### PR DESCRIPTION
**Pull request by olamy**
- add `@Symbol` to be able to easily use the plugin in a declarative pipeline
- add support for incremental

### CODE REVIEW

**Comment by olamy** [comment]
@dmone @ffromm any chance to have this little enhancement merged and release? Thanks

**Review by jglick — CHANGES_REQUESTED** [review]
Incrementals not working. File something in helpdesk.

**Comment by jglick** [comment]
Ah. https://github.com/jenkinsci/build-blocker-plugin/blob/bc530da7376d2aa08b0f56f212532fda72b18f8d/pom.xml#L32 is super old. Update, and switch to Java 11.

**Comment by olamy** [comment]
> Ah.
> 
> https://github.com/jenkinsci/build-blocker-plugin/blob/bc530da7376d2aa08b0f56f212532fda72b18f8d/pom.xml#L32
> 
> is super old. Update, and switch to Java 11.

At this stage, I need some approvals of such upgrade by the maintainers and don't want to mix such an upgrade with the new feature of this PR

**Comment by jglick** [comment]
Makes sense. Anyway, https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/build-blocker-plugin/1.7.9-rc163.0c9941f0b_a_51/ worked.

**Comment by jonesbusy** [comment]
+ here. I was looking for such option on this plugin

**Comment by olamy** [comment]
@dmone @ffromm ping :)

**Comment by Denis1990** [comment]
Hello @olamy. Thank you for your contribution.
I am sorry i didn't respond earlier, i was on holidays and it seems i didn't get any notification from Github about the mentions.
I am currently reviewing the PR.

**Comment by Denis1990** [comment]
Testing out the change locally
I checked the pr code, built it locally and brought up a Jenkins instance with 
 - git fetch origin pull/19/head:declarative_syntax && git checkout declarative_syntax
 - JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64/ mvn clean hpi:run
In the meantime i modified pom.xml and added some pipeline dependencies.
I also brought up a couple of docker containers to act as Jenkins agents 
```docker run -i --rm --network="host" \ 
   --name agent1 --init -v agent1:/home/jenkins/agent jenkins/agent:4.10-2-jdk11 \
   java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://127.0.0.1:8080/jenkins/computer/agent1/slave-agent.jnlp```

I created a couple of pipelines each blocking each blocking each other while running on the same node

The blocking worked, as expected.

Will merge and release.

**Pull request merged**
